# Generated by Django 6.0.6 on 2026-06-28 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabanas', '0001_initial'),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadCabanas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=True)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('Cabanas
', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabanas.Cabanas
')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
