services:
  - type: web
    name: alquileres-cabanas
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn alquileres_cabanas.wsgi:application"
    plan: free
    autoDeploy: true
