# Generated by Django 6.0.4 on 2026-05-07 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Cabaña')),
                ('capacidad_clientes', models.PositiveIntegerField(default=2)),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('esta_activa', models.BooleanField(default=True, verbose_name='Disponible para alquilar')),
            ],
            options={
                'verbose_name': 'Cabaña',
                'verbose_name_plural': 'Cabañas',
            },
        ),
        migrations.CreateModel(
            name='RegistroDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('novedades', models.TextField(help_text='Ej: Se rompió una lamparita, limpieza realizada, etc.')),
                ('fue_limpiada', models.BooleanField(default=False)),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_diarios', to='registros.cabana')),
            ],
            options={
                'verbose_name': 'Registro Diario',
                'verbose_name_plural': 'Registros Diarios',
            },
        ),
    ]
