# Generated by Django 6.0.5 on 2026-05-26 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabana_apps', '0001_initial'),
        ('registros', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodiario',
            name='cabana_gestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_diarios', to='cabana_apps.cabana', verbose_name='Cabana gestion'),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='cabana_reservas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_diarios', to='reservas.cabana', verbose_name='Cabana reservas'),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='reserva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_diarios', to='reservas.reserva'),
        ),
        migrations.AddField(
            model_name='registrodiario',
            name='reserva_gestion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_diarios', to='cabana_apps.reserva', verbose_name='Reserva gestion'),
        ),
    ]
