# Generated by Django 6.0.5 on 2026-06-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabana_apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('modulo', models.CharField(choices=[('clientes', 'Clientes'), ('reservas', 'Reservas'), ('alquileres', 'Alquileres'), ('pagos', 'Pagos')], max_length=20)),
                ('descripcion', models.TextField()),
                ('responsable', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='activo', max_length=20)),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabana_apps.cabana')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabana_apps.cliente')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cabana_apps.reserva')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta')], default='efectivo', max_length=20)),
                ('comprobante', models.CharField(blank=True, max_length=120)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabana_apps.alquiler')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
