# Generated by Django 4.2 on 2026-06-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabanas
',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=True)),
                ('nombre', models.CharField(max_length=200)),
                ('capacidad', models.PositiveIntegerField(default=1)),
                ('precio_dia', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('precio_por_persona', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ocupada', models.BooleanField(default=True)),
                ('habilitada', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
    ]
