# Generated by Django 6.1.1 on 2026-09-14 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alquileres', '0001_initial'),
        ('cabanas', '0001_initial'),
        ('clientes', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alquiler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_alquiler', to='alquileres.alquiler')),
                ('cabana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_cabana', to='cabanas.cabana')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_cliente', to='clientes.cliente')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_reserva', to='reservas.reserva')),
            ],
        ),
    ]
