# Generated by Django 6.0.6 on 2026-06-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabana',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cabana',
                'verbose_name_plural': 'Cabanas',
            },
        ),
    ]
