# Generated by Django 6.0.6 on 2026-06-28 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabanas', '0001_initial'),
        ('clientes', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('cabanas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabanas.cabana')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
            ],
        ),
    ]
